spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_example
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    showSql: true
    hibernate:
      ddlAuto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect